<?xml version="1.0" encoding="utf-8"?><Database Name="QuanlyLuat" Class="MydataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\QuanlyLuat.mdf;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanlyLuatConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Luat" Member="Luats">
    <Type Name="Luat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Chuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NDChuong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Muc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NDMuc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Dieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NDDieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Khoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NDKhoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MucPhatduoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MucPhattren" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QAQC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>